// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: true,
  version: env['npm_package_version'],
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'es-ES',
  supportedLanguages: ['es-ES'],
  firebaseConfig: {
    apiKey: 'AIzaSyAdeQ8C9XDH573skle1j5iBZkhdbabGb6Q',
    authDomain: 'testprimos-9f796.firebaseapp.com',
    projectId: 'testprimos-9f796',
    storageBucket: 'testprimos-9f796.appspot.com',
    messagingSenderId: '589828977270',
    appId: '1:589828977270:web:452163c5882fc05a78e557',
    measurementId: 'G-MVHCWP6BG5',
  },
};
